import { Product, Testimonial } from './types';

export const PRODUCTS: Product[] = [
  // --- SWEATERS ---
  {
    id: '1',
    name: 'Vintage Rose Cardigan',
    category: 'Sweaters',
    price: 85,
    image: 'https://images.unsplash.com/photo-1620799140408-ed5341cd2431?auto=format&fit=crop&q=80&w=800',
    description: 'A chunky, hand-knit cardigan featuring soft rose patterns and wooden buttons. Perfect for chilly evenings.',
    materials: '60% Wool, 40% Acrylic blend for softness and durability.',
    care: 'Hand wash cold, lay flat to dry.',
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Honeycomb Mustard Pullover',
    category: 'Sweaters',
    price: 95,
    image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800',
    description: 'Bright and cheerful pullover with a textured honeycomb stitch. The oversized fit makes it incredibly cozy.',
    materials: '100% Merino Wool.',
    care: 'Hand wash cold, reshape while damp.',
    isFeatured: false,
  },
  {
    id: '9',
    name: 'Midnight Blue Cable Vest',
    category: 'Sweaters',
    price: 55,
    image: 'https://images.unsplash.com/photo-1621087363677-4b95eb7c0413?auto=format&fit=crop&q=80&w=800',
    description: 'A classic cable knit vest in deep navy blue. Perfect for layering over white collared shirts.',
    materials: 'Acrylic/Wool blend.',
    care: 'Machine wash gentle.',
    isFeatured: false,
  },
  {
    id: '10',
    name: 'Granny Square Patchwork Coat',
    category: 'Sweaters',
    price: 150,
    image: 'https://images.unsplash.com/photo-1608234808654-2a8875b7b09c?auto=format&fit=crop&q=80&w=800',
    description: 'A statement piece featuring vibrant vintage-style granny squares. Each coat is unique.',
    materials: '100% Cotton Yarn.',
    care: 'Hand wash only, dry flat.',
    isFeatured: true,
  },
  {
    id: '11',
    name: 'Cream Puff Crop Top',
    category: 'Sweaters',
    price: 45,
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&q=80&w=800',
    description: 'Lightweight and airy crop top with balloon sleeves. Ideal for spring festivals.',
    materials: 'Bamboo yarn.',
    care: 'Machine wash cold.',
    isFeatured: false,
  },

  // --- BAGS ---
  {
    id: '2',
    name: 'Sage Green Market Bag',
    category: 'Bags',
    price: 35,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&q=80&w=800',
    description: 'Eco-friendly and stylish. This sturdy market bag expands to fit all your groceries or beach essentials.',
    materials: '100% Cotton yarn.',
    care: 'Machine wash gentle, hang dry.',
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Boho Fringe Crossbody',
    category: 'Bags',
    price: 55,
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800',
    description: 'A festival-ready bag with playful fringe details and a secure button closure.',
    materials: 'Recycled cotton cord.',
    care: 'Spot clean only.',
    isFeatured: false,
  },
  {
    id: '12',
    name: 'Sunflower Tote Bag',
    category: 'Bags',
    price: 45,
    image: 'https://images.unsplash.com/photo-1597484662317-9bd7bdda2907?auto=format&fit=crop&q=80&w=800',
    description: 'Large sturdy tote composed of joined sunflower squares. Lined with canvas for extra durability.',
    materials: 'Acrylic yarn, Canvas lining.',
    care: 'Spot clean.',
    isFeatured: false,
  },
  {
    id: '13',
    name: 'Mini Phone Pouch',
    category: 'Bags',
    price: 25,
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=800',
    description: 'Keep your phone safe and hands-free. Features a long strap and magnetic snap.',
    materials: 'Cotton yarn.',
    care: 'Machine wash cold.',
    isFeatured: false,
  },
  {
    id: '14',
    name: 'Drawstring Backpack',
    category: 'Bags',
    price: 65,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    description: 'A roomy backpack with a secure drawstring closure and flap. Great for day trips.',
    materials: 'Heavy duty cotton blend.',
    care: 'Hand wash.',
    isFeatured: false,
  },

  // --- BABY ---
  {
    id: '3',
    name: 'Sleepy Bear Baby Blanket',
    category: 'Baby',
    price: 60,
    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&q=80&w=800',
    description: 'Incredibly soft heirloom blanket in pastel tones. Hypoallergenic and gentle on baby skin.',
    materials: '100% Bamboo-Cotton blend.',
    care: 'Machine wash cold on delicate cycle.',
    isFeatured: true,
  },
  {
    id: '7',
    name: 'Custom Amigurumi Bunny',
    category: 'Baby',
    price: 40,
    image: 'https://images.unsplash.com/photo-1559461123-b88307409247?auto=format&fit=crop&q=80&w=800',
    description: 'Adorable crochet stuffed bunny. Customizable bow tie color. Safety eyes used.',
    materials: 'Cotton yarn, polyester filling.',
    care: 'Spot clean or gentle hand wash.',
    isFeatured: true,
  },
  {
    id: '15',
    name: 'Newborn Booties Set',
    category: 'Baby',
    price: 25,
    image: 'https://images.unsplash.com/photo-1522771753035-1a5b6562f3ba?auto=format&fit=crop&q=80&w=800',
    description: 'Set of two pairs of newborn booties. One cream, one soft grey. Adjustable ankle ties.',
    materials: 'Soft merino wool.',
    care: 'Hand wash.',
    isFeatured: false,
  },
  {
    id: '16',
    name: 'Fox Hooded Cowl',
    category: 'Baby',
    price: 45,
    image: 'https://images.unsplash.com/photo-1610173824250-681b4712ccb3?auto=format&fit=crop&q=80&w=800',
    description: 'Keep little ears warm with this adorable fox-themed hood and cowl combo.',
    materials: 'Acrylic yarn.',
    care: 'Machine wash gentle.',
    isFeatured: false,
  },
  {
    id: '17',
    name: 'Pastel Rattle Teether',
    category: 'Baby',
    price: 18,
    image: 'https://images.unsplash.com/photo-1515488042361-25f4682ee049?auto=format&fit=crop&q=80&w=800',
    description: 'Natural wood ring with a crocheted animal topper. Includes a gentle rattle sound.',
    materials: 'Organic cotton, untreated wood.',
    care: 'Wipe clean.',
    isFeatured: false,
  },

  // --- ACCESSORIES ---
  {
    id: '4',
    name: 'Autumn Spice Scarf',
    category: 'Accessories',
    price: 45,
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800',
    description: 'Long, textured scarf in warm burnt orange and cinnamon tones. Wrap yourself in cozy comfort.',
    materials: 'Merino Wool.',
    care: 'Hand wash only.',
    isFeatured: false,
  },
  {
    id: '6',
    name: 'Cozy Cable Knit Beanie',
    category: 'Accessories',
    price: 30,
    image: 'https://images.unsplash.com/photo-1576033065386-db016b06380e?auto=format&fit=crop&q=80&w=800',
    description: 'Classic cable knit design with a fluffy faux-fur pompom. Available in cream, grey, and navy.',
    materials: 'Soft acrylic wool.',
    care: 'Hand wash, avoid wetting the pompom.',
    isFeatured: false,
  },
  {
    id: '18',
    name: 'Twist Headband',
    category: 'Accessories',
    price: 20,
    image: 'https://images.unsplash.com/photo-1582234032549-9aa806b1e62c?auto=format&fit=crop&q=80&w=800',
    description: 'Chunky ear warmer with a stylish twist detail. Perfect for messy buns.',
    materials: 'Velvet yarn.',
    care: 'Machine wash cold.',
    isFeatured: false,
  },
  {
    id: '19',
    name: 'Fingerless Writing Gloves',
    category: 'Accessories',
    price: 28,
    image: 'https://images.unsplash.com/photo-1542283084-25e1741164ef?auto=format&fit=crop&q=80&w=800',
    description: 'Keep your hands warm while typing or texting. Beautiful moss stitch texture.',
    materials: 'Alpaca blend.',
    care: 'Hand wash.',
    isFeatured: false,
  },
  {
    id: '20',
    name: 'Crochet Bucket Hat',
    category: 'Accessories',
    price: 35,
    image: 'https://images.unsplash.com/photo-1623941008629-4d3cb6217482?auto=format&fit=crop&q=80&w=800',
    description: 'Trendy checkerboard pattern bucket hat. A summer essential.',
    materials: '100% Cotton.',
    care: 'Machine wash cold.',
    isFeatured: false,
  },

  // --- HOME ---
  {
    id: '21',
    name: 'Boho Hanging Planter',
    category: 'Home',
    price: 22,
    image: 'https://images.unsplash.com/photo-1591104886676-e10ddc27598c?auto=format&fit=crop&q=80&w=800',
    description: 'Add greenery to your space with this macrame-style crochet plant hanger.',
    materials: 'Jute twine.',
    care: 'Spot clean.',
    isFeatured: false,
  },
  {
    id: '22',
    name: 'Textured Throw Pillow',
    category: 'Home',
    price: 50,
    image: 'https://images.unsplash.com/photo-1579656381282-b715a2eb9153?auto=format&fit=crop&q=80&w=800',
    description: 'Bobble stitch pillow cover in neutral cream. Adds instant texture to your sofa.',
    materials: 'Acrylic yarn.',
    care: 'Machine wash cover separately.',
    isFeatured: false,
  },
  {
    id: '23',
    name: 'Floral Coaster Set',
    category: 'Home',
    price: 15,
    image: 'https://images.unsplash.com/photo-1616428612740-49651a2d1316?auto=format&fit=crop&q=80&w=800',
    description: 'Set of 4 flower-shaped coasters. Protects your table in style.',
    materials: 'Cotton yarn.',
    care: 'Machine wash warm.',
    isFeatured: false,
  },
  {
    id: '24',
    name: 'Rustic Table Runner',
    category: 'Home',
    price: 65,
    image: 'https://images.unsplash.com/photo-1596238696803-b097b6951233?auto=format&fit=crop&q=80&w=800',
    description: 'Lace design table runner. Adds a vintage cottage-core vibe to your dining room.',
    materials: 'Mercerized cotton.',
    care: 'Hand wash, block to dry.',
    isFeatured: false,
  },
  {
    id: '25',
    name: 'Chunky Floor Pouf',
    category: 'Home',
    price: 120,
    image: 'https://images.unsplash.com/photo-1589218672023-e5d80099897d?auto=format&fit=crop&q=80&w=800',
    description: 'Oversized floor cushion made with ultra-thick yarn. Perfect for meditation or extra seating.',
    materials: 'Tube yarn (Cotton/Polyester).',
    care: 'Spot clean only.',
    isFeatured: true,
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: "Sarah M.",
    text: "I bought the baby blanket for my niece, and it is the softest thing ever! You can really feel the love in every stitch.",
    location: "Nairobi"
  },
  {
    id: 2,
    name: "Jessica K.",
    text: "Fatma's cardigans are my winter staple. They fit perfectly and the quality is far better than anything from a big store.",
    location: "Mombasa"
  },
  {
    id: 3,
    name: "Amani J.",
    text: "Ordered a custom bag for my wedding favors. Fatma was so patient with my requests. Highly recommended!",
    location: "Kisumu"
  }
];

export const WHATSAPP_NUMBER = "254759094016";